[package]

name = "num"
version = "0.1.28"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/rust-num/num"
repository = "https://github.com/rust-num/num"
documentation = "http://rust-num.github.io/num"
keywords = ["mathematics", "numerics"]
description = """
A collection of numeric types and traits for Rust, including bigint,
complex, rational, range iterators, generic integers, and more!
"""

[dependencies]
rustc-serialize = { version = "0.3.13", optional = true }
rand = { version = "0.3.8", optional = true }

[features]

complex = []
rational = []
bigint = ["rustc-serialize", "rand"]
default = ["complex", "rational", "bigint"]

[[bench]]
name = "bigint"

[[bench]]
name = "shootout-pidigits"
harness = false

[profile.release]
debug = true

[profile.benchmark]
debug = true
